services:
  - type: web
    name: bot-gmgm-dashboard
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run dashboard.py --server.port $PORT --server.address=0.0.0.0
    envVars:
      - key: DISCORD_TOKEN
        fromDatabase:
          name: bot-gmgm-secrets
          key: DISCORD_TOKEN
