services:
  - type: web
    name: bot-gm-dashboard
    env: python
    region: oregon  # ou o mais próximo de você, como 'frankfurt'
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run dashboard.py --server.port $PORT --server.address=0.0.0.0
    autoDeploy: true